# https://taskfile.dev

version: "3"

interval: 100ms
vars:
  GREETING: Hello, World!
  NAME: "natschat"
  BIN_NAME: "{{.NAME}}_bin"

tasks:
  tailwind:
    dir: ./frontend/gen/css
    generates:
      - "../../static/tailwind.css"
    sources:
      - "../../**/*.go"
    cmds:
      - pnpm i
      - pnpm tailwindcss -o ../../static/tailwind.css

  kill:
    cmds:
      - killall -q {{.BIN_NAME}}  || echo "Process was not running."

  hot:
    desc: Server hot reload

    sources:
      - "**/*.go"
      - "**/*.sql"
    deps:
      - kill
      - tailwind
    cmds:
      - go mod tidy
      - go build -o ./{{.BIN_NAME}} cmd/{{.NAME}}/*.go
      - ./{{.BIN_NAME}}

  default:
    deps:
      - hot
    silent: true
